apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-kdo6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-kdo6
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-kdo6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-kdo6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-kdo6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hgum-tenant/nodejs-users/simple-nodejs-app-kdo6@sha256:5df7528a1e159d3f2c3ab7c6c57cf658e427b442f842d9b41eb41ff90aecfa00
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
